# Generated by Django 3.2.15 on 2022-08-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Idb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idb',
            name='mshuyunpan',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='idb',
            name='subgroup_download',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='idb',
            name='subgroup_from',
            field=models.URLField(),
        ),
    ]
